#!/usr/bin/env bash

# Safety first
set -o errexit -o pipefail -o nounset
# Change into the project's directory
cd "$(dirname "$0")/.."

# Run the checks
uv run ruff format
uv run ruff check --fix
uv run ty check
